// <auto-generated />
using System;
using FinancialEvaluationApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinancialEvaluationApp.Migrations
{
    [DbContext(typeof(FinancialEvaluationDbContext))]
    partial class FinancialEvaluationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FinancialEvaluationApp.Models.Core.Bidder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NationalId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Bidders");
                });

            modelBuilder.Entity("FinancialEvaluationApp.Models.Core.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("ParentCompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RegistrationNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("ParentCompanyId");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("FinancialEvaluationApp.Models.Core.EvaluationResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BidderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("FinalScore")
                        .HasColumnType("decimal(18,4)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PriceScore")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int?>("Rank")
                        .HasColumnType("int");

                    b.Property<decimal>("TechnicalScore")
                        .HasColumnType("decimal(18,4)");

                    b.Property<Guid>("TenderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("BidderId");

                    b.HasIndex("TenderId");

                    b.ToTable("EvaluationResults");
                });

            modelBuilder.Entity("FinancialEvaluationApp.Models.Core.Proposal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BidderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal?>("ForeignAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("ForeignCurrencyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("FxRate")
                        .HasColumnType("decimal(18,6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal?>("NormalizedAmountIRR")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProposalNo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("RialAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("TenderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("BidderId");

                    b.HasIndex("ForeignCurrencyId");

                    b.HasIndex("TenderId");

                    b.ToTable("Proposals");
                });

            modelBuilder.Entity("FinancialEvaluationApp.Models.Core.Tender", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("BaseEstimateAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset?>("ClosingDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("PublishDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Tenders");
                });

            modelBuilder.Entity("FinancialEvaluationApp.Models.RefData.Currency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("DefaultFxRateToIRR")
                        .HasColumnType("decimal(18,6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Currencies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Code = "IRR",
                            IsActive = true,
                            IsDefault = true,
                            Name = "Iranian Rial",
                            SortOrder = 1,
                            Symbol = "﷼"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Code = "USD",
                            IsActive = true,
                            IsDefault = false,
                            Name = "US Dollar",
                            SortOrder = 2,
                            Symbol = "$"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Code = "EUR",
                            IsActive = true,
                            IsDefault = false,
                            Name = "Euro",
                            SortOrder = 3,
                            Symbol = "€"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Code = "AED",
                            IsActive = true,
                            IsDefault = false,
                            Name = "UAE Dirham",
                            SortOrder = 4,
                            Symbol = "AED"
                        });
                });

            modelBuilder.Entity("FinancialEvaluationApp.Models.RefData.FxRate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BaseCurrencyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid>("QuoteCurrencyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18,6)");

                    b.Property<DateTimeOffset>("RateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BaseCurrencyId");

                    b.HasIndex("QuoteCurrencyId");

                    b.ToTable("FxRates");
                });

            modelBuilder.Entity("FinancialEvaluationApp.Models.Core.Bidder", b =>
                {
                    b.HasOne("FinancialEvaluationApp.Models.Core.Company", "Company")
                        .WithMany("Bidders")
                        .HasForeignKey("CompanyId");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("FinancialEvaluationApp.Models.Core.Company", b =>
                {
                    b.HasOne("FinancialEvaluationApp.Models.Core.Company", "ParentCompany")
                        .WithMany("Subsidiaries")
                        .HasForeignKey("ParentCompanyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentCompany");
                });

            modelBuilder.Entity("FinancialEvaluationApp.Models.Core.EvaluationResult", b =>
                {
                    b.HasOne("FinancialEvaluationApp.Models.Core.Bidder", "Bidder")
                        .WithMany("EvaluationResults")
                        .HasForeignKey("BidderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinancialEvaluationApp.Models.Core.Tender", "Tender")
                        .WithMany("EvaluationResults")
                        .HasForeignKey("TenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bidder");

                    b.Navigation("Tender");
                });

            modelBuilder.Entity("FinancialEvaluationApp.Models.Core.Proposal", b =>
                {
                    b.HasOne("FinancialEvaluationApp.Models.Core.Bidder", "Bidder")
                        .WithMany("Proposals")
                        .HasForeignKey("BidderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinancialEvaluationApp.Models.RefData.Currency", "ForeignCurrency")
                        .WithMany()
                        .HasForeignKey("ForeignCurrencyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FinancialEvaluationApp.Models.Core.Tender", "Tender")
                        .WithMany("Proposals")
                        .HasForeignKey("TenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bidder");

                    b.Navigation("ForeignCurrency");

                    b.Navigation("Tender");
                });

            modelBuilder.Entity("FinancialEvaluationApp.Models.Core.Tender", b =>
                {
                    b.HasOne("FinancialEvaluationApp.Models.Core.Company", "Company")
                        .WithMany("Tenders")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("FinancialEvaluationApp.Models.RefData.FxRate", b =>
                {
                    b.HasOne("FinancialEvaluationApp.Models.RefData.Currency", "BaseCurrency")
                        .WithMany()
                        .HasForeignKey("BaseCurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FinancialEvaluationApp.Models.RefData.Currency", "QuoteCurrency")
                        .WithMany()
                        .HasForeignKey("QuoteCurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BaseCurrency");

                    b.Navigation("QuoteCurrency");
                });

            modelBuilder.Entity("FinancialEvaluationApp.Models.Core.Bidder", b =>
                {
                    b.Navigation("EvaluationResults");

                    b.Navigation("Proposals");
                });

            modelBuilder.Entity("FinancialEvaluationApp.Models.Core.Company", b =>
                {
                    b.Navigation("Bidders");

                    b.Navigation("Subsidiaries");

                    b.Navigation("Tenders");
                });

            modelBuilder.Entity("FinancialEvaluationApp.Models.Core.Tender", b =>
                {
                    b.Navigation("EvaluationResults");

                    b.Navigation("Proposals");
                });
#pragma warning restore 612, 618
        }
    }
}
